version: '3.9'
services:

  json-server:
    
    build: ./frontedm8/database
    ports:
      - 5000:5000

  frontend-dev:
    
    restart: always
    build: ./frontedm8
      context: ./frontedm8
      dockerfile: Dockerfile.dev
    ports: 
      - 3303:3303
    environment:
      NODE_ENV: dev
    depends_on:
      - json-server

  frontend-test:
    
    restart: always
    build: ./frontedm8
      context: ./frontedm8
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
    depends_on:
      - json-server

  frontend-prod:
    
    restart: always
    build: ./frontedm8
    ports: 
      - 8086:80
    environment:
      NODE_ENV: prod
    depends_on:
      - json-server
  

      